openapi: 3.2.0
info:
  title: Assembly Marketplaces API
  description: Assembly (formely PromisePay) is a powerful payments engine custom-built for platforms and marketplaces.
  version: '2.3'
  contact:
    email: support@assemblypayments.com
    url: http://docs.assemblypayments.com/
servers:
- url: https://test.api.promisepay.com
  description: Pre-live environment
- url: https://secure.api.promisepay.com
  description: Production environment
- url: https://au-0000.sandbox.auth.assemblypay.com
  description: Pre-Live (Sandbox) Auth issuing server and API
- url: https://au-0000.auth.assemblypay.com
  description: Production Auth issuing server and API
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/AssemblyPlatforms/assembly-api/2.3
security:
- oAuth2ClientCredentials: []
tags:
- name: Marketplaces
paths:
  /marketplace:
    get:
      tags:
      - Marketplaces
      summary: Show Marketplace
      description: Show details of your **Platform**, providing access to your configuration and related **User** and **Company**.
      operationId: showMarketplace
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/marketplace'
              examples:
                response:
                  value:
                    marketplaces:
                      id: 041e8015-5101-44f1-9b7d-6a206603f29f
                      group_name: null
                      name: platform1556505750
                      short_name: null
                      color_1: null
                      color_2: null
                      color_3: null
                      color_4: null
                      color_5: null
                      website: null
                      payment_frequency: daily
                      alt_marketplace_id: null
                      state: pending
                      logo: null
                      active: true
                      alt_marketplace_auth: null
                      disable_approve_logo: false
                      enable_virtual_terminal: false
                      currency: AUD
                      email: ausplatform1556505750@assemblypayments.com
                      seller_white_labeled: false
                      partial_refunds: true
                      related:
                        users: 76cf57db94d9e1f07a60c009be2adec0
                        company: 5ba45160-4c56-0137-55f0-0242ac110002
                      links:
                        self: /marketplace
                        principal: /users/76cf57db94d9e1f07a60c009be2adec0
                        company: /companies/5ba45160-4c56-0137-55f0-0242ac110002
components:
  schemas:
    marketplace:
      type: object
      properties:
        marketplaces:
          type: object
          properties:
            id:
              type: string
            group_name:
              type: string
            name:
              type: string
            short_name:
              type: string
            color_1:
              type: string
            color_2:
              type: string
            color_3:
              type: string
            color_4:
              type: string
            color_5:
              type: string
            website:
              type: string
            payment_frequency:
              type: string
            alt_marketplace_id:
              type: string
            state:
              type: string
            logo:
              type: string
            active:
              type: string
            alt_marketplace_auth:
              type: string
            disable_approve_logo:
              type: boolean
            enable_virtual_terminal:
              type: boolean
            currency:
              type: string
            email:
              type: string
            seller_white_labeled:
              type: boolean
            partial_refunds:
              type: boolean
            related:
              type: object
              properties:
                users:
                  type: string
                company:
                  type: string
            links:
              type: object
              properties:
                self:
                  type: string
                principal:
                  type: string
                company:
                  type: string
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      description: Please refer to Authentication section within https://developer.assemblypayments.com/reference#authentication
      flows:
        clientCredentials:
          tokenUrl: https://au-0000.sandbox.auth.assemblypay.com/tokens
          scopes: {}
x-explorer-enabled: false
x-samples-languages:
- curl
- ruby
- php
- javascript
- csharp
- go
x-proxy-enabled: true
x-samples-enabled: true
